codecov:
  token: 3806b863-7185-4be7-9787-a0c1d7963703
  notify:
    slack:
      url: "https://hooks.slack.com/services/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"
      # only_pulls: false
      attachments: "sunburst, diff"
      # branches: default

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no
    threshold: 2


parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
